# Welcome to Jupyter!

In [2]:
import pandas

In [8]:
table = pandas.read_csv('http://webstat.banque-france.fr/fr/downloadFile.do?id=5385698&exportType=csv', header=None, delimiter= ';', nrows = 6)

In [9]:
table.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Titre :,Dollar australien (AUD),Lev bulgare (BGN),Real brésilien (BRL),Dollar canadien (CAD),Franc suisse (CHF),Yuan renminbi chinois (CNY),Livre chypriote (CYP),Couronne tchèque (CZK),Couronne danoise (DKK),...,Leu roumain (RON),Rouble russe (RUB),Couronne suédoise (SEK),Dollar de Singapour (SGD),Tolar slovène (SIT),Couronne slovaque (SKK),Baht thaïlandais (THB),Livre turque (TRY),Dollar des Etats-Unis (USD),Rand sud-africain (ZAR)
1,Code série :,EXR.D.AUD.EUR.SP00.A,EXR.D.BGN.EUR.SP00.A,EXR.D.BRL.EUR.SP00.A,EXR.D.CAD.EUR.SP00.A,EXR.D.CHF.EUR.SP00.A,EXR.D.CNY.EUR.SP00.A,EXR.D.CYP.EUR.SP00.A,EXR.D.CZK.EUR.SP00.A,EXR.D.DKK.EUR.SP00.A,...,EXR.D.RON.EUR.SP00.A,EXR.D.RUB.EUR.SP00.A,EXR.D.SEK.EUR.SP00.A,EXR.D.SGD.EUR.SP00.A,EXR.D.SIT.EUR.SP00.A,EXR.D.SKK.EUR.SP00.A,EXR.D.THB.EUR.SP00.A,EXR.D.TRY.EUR.SP00.A,EXR.D.USD.EUR.SP00.A,EXR.D.ZAR.EUR.SP00.A
2,Unité :,Dollar Australien (AUD),Lev Nouveau (BGN),Real Bresilien (BRL),Dollar Canadien (CAD),Franc Suisse (CHF),Yuan Ren Min Bi (CNY),Livre Cypriote (CYP),Couronne Tcheque (CZK),Couronne Danoise (DKK),...,Nouveau Ron (RON),Rouble Russe (RUB) (RUB),Couronne Suedoise (SEK),Dollar de Singapour (SGD),Tolar (SIT),Couronne Slovaque (SKK),Baht (THB),Nouvelle Livre Turque (TRY),Dollar des Etats-Unis (USD),Rand (ZAR)
3,Magnitude :,Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),...,Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0)
4,Méthode d'observation :,Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),...,Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A)

In [10]:
table = table.T

In [11]:
table.head()

,0,1,2,3,4,5
0,Titre :,Code série :,Unité :,Magnitude :,Méthode d'observation :,Source :
1,Dollar australien (AUD),EXR.D.AUD.EUR.SP00.A,Dollar Australien (AUD),Unités (0),Moyenne de la période (A),BCE (Banque Centrale Européenne) (4F0)
2,Lev bulgare (BGN),EXR.D.BGN.EUR.SP00.A,Lev Nouveau (BGN),Unités (0),Moyenne de la période (A),BCE (Banque Centrale Européenne) (4F0)
3,Real brésilien (BRL),EXR.D.BRL.EUR.SP00.A,Real Bresilien (BRL),Unités (0),Moyenne de la période (A),BCE (Banque Centrale Européenne) (4F0)
4,Dollar canadien (CAD),EXR.D.CAD.EUR.SP00.A,Dollar Canadien (CAD),Unités (0),Moyenne de la période (A),BCE (Banque Centrale Européenne) (4F0)

In [3]:
dates = pandas.read_csv('http://webstat.banque-france.fr/fr/downloadFile.do?id=5385698&exportType=csv', header=None, delimiter= ';')

In [4]:
dates.head(n=10)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Titre :,Dollar australien (AUD),Lev bulgare (BGN),Real brésilien (BRL),Dollar canadien (CAD),Franc suisse (CHF),Yuan renminbi chinois (CNY),Livre chypriote (CYP),Couronne tchèque (CZK),Couronne danoise (DKK),...,Leu roumain (RON),Rouble russe (RUB),Couronne suédoise (SEK),Dollar de Singapour (SGD),Tolar slovène (SIT),Couronne slovaque (SKK),Baht thaïlandais (THB),Livre turque (TRY),Dollar des Etats-Unis (USD),Rand sud-africain (ZAR)
1,Code série :,EXR.D.AUD.EUR.SP00.A,EXR.D.BGN.EUR.SP00.A,EXR.D.BRL.EUR.SP00.A,EXR.D.CAD.EUR.SP00.A,EXR.D.CHF.EUR.SP00.A,EXR.D.CNY.EUR.SP00.A,EXR.D.CYP.EUR.SP00.A,EXR.D.CZK.EUR.SP00.A,EXR.D.DKK.EUR.SP00.A,...,EXR.D.RON.EUR.SP00.A,EXR.D.RUB.EUR.SP00.A,EXR.D.SEK.EUR.SP00.A,EXR.D.SGD.EUR.SP00.A,EXR.D.SIT.EUR.SP00.A,EXR.D.SKK.EUR.SP00.A,EXR.D.THB.EUR.SP00.A,EXR.D.TRY.EUR.SP00.A,EXR.D.USD.EUR.SP00.A,EXR.D.ZAR.EUR.SP00.A
2,Unité :,Dollar Australien (AUD),Lev Nouveau (BGN),Real Bresilien (BRL),Dollar Canadien (CAD),Franc Suisse (CHF),Yuan Ren Min Bi (CNY),Livre Cypriote (CYP),Couronne Tcheque (CZK),Couronne Danoise (DKK),...,Nouveau Ron (RON),Rouble Russe (RUB) (RUB),Couronne Suedoise (SEK),Dollar de Singapour (SGD),Tolar (SIT),Couronne Slovaque (SKK),Baht (THB),Nouvelle Livre Turque (TRY),Dollar des Etats-Unis (USD),Rand (ZAR)
3,Magnitude :,Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),...,Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0),Unités (0)
4,Méthode d'observation :,Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),...,Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A),Moyenne de la période (A)
5,Source :,BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),...,BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0),BCE (Banque Centrale Européenne) (4F0)
6,23/04/2021,"1,559","1,9558","6,5572","1,5062","1,1038","7,832",NaN,"25,847","7,4361",...,"4,9245","90,3287","10,1405","1,601",NaN,NaN,"37,85","10,0635","1,2066","17,2068"
7,22/04/2021,"1,5581","1,9558","6,6546","1,5067","1,1035","7,8181",NaN,"25,86","7,4366",...,"4,9274","91,3275","10,1237","1,6001",NaN,NaN,"37,77","9,9553","1,2046","17,2348"
8,21/04/2021,"1,5554","1,9558","6,6869","1,5137","1,1026","7,8011",NaN,"25,893","7,4364",...,"4,926","92,0836","10,1513","1,5971",NaN,NaN,"37,666","9,8156","1,2007","17,145"
9,20/04/2021,"1,5492","1,9558","6,7117","1,5089","1,1029","7,8303",NaN,"25,903","7,4365",...,"4,9278","92,2786","10,1288","1,6009",NaN,NaN,"37,69","9,7764","1,2051","17,2287"

In [5]:
dates = dates.drop([1,2,3,4,5])

In [6]:
dates.head(10)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Titre :,Dollar australien (AUD),Lev bulgare (BGN),Real brésilien (BRL),Dollar canadien (CAD),Franc suisse (CHF),Yuan renminbi chinois (CNY),Livre chypriote (CYP),Couronne tchèque (CZK),Couronne danoise (DKK),...,Leu roumain (RON),Rouble russe (RUB),Couronne suédoise (SEK),Dollar de Singapour (SGD),Tolar slovène (SIT),Couronne slovaque (SKK),Baht thaïlandais (THB),Livre turque (TRY),Dollar des Etats-Unis (USD),Rand sud-africain (ZAR)
6,23/04/2021,"1,559","1,9558","6,5572","1,5062","1,1038","7,832",NaN,"25,847","7,4361",...,"4,9245","90,3287","10,1405","1,601",NaN,NaN,"37,85","10,0635","1,2066","17,2068"
7,22/04/2021,"1,5581","1,9558","6,6546","1,5067","1,1035","7,8181",NaN,"25,86","7,4366",...,"4,9274","91,3275","10,1237","1,6001",NaN,NaN,"37,77","9,9553","1,2046","17,2348"
8,21/04/2021,"1,5554","1,9558","6,6869","1,5137","1,1026","7,8011",NaN,"25,893","7,4364",...,"4,926","92,0836","10,1513","1,5971",NaN,NaN,"37,666","9,8156","1,2007","17,145"
9,20/04/2021,"1,5492","1,9558","6,7117","1,5089","1,1029","7,8303",NaN,"25,903","7,4365",...,"4,9278","92,2786","10,1288","1,6009",NaN,NaN,"37,69","9,7764","1,2051","17,2287"
10,19/04/2021,"1,5491","1,9558","6,7056","1,5038","1,0998","7,8323",NaN,"25,903","7,4364",...,"4,926","91,7527","10,0985","1,6014",NaN,NaN,"37,589","9,7198","1,2035","17,1398"
11,18/04/2021,-,-,-,-,-,-,NaN,-,-,...,-,-,-,-,NaN,NaN,-,-,-,-
12,17/04/2021,-,-,-,-,-,-,NaN,-,-,...,-,-,-,-,NaN,NaN,-,-,-,-
13,16/04/2021,"1,5459","1,9558","6,74","1,4986","1,1011","7,8157",NaN,"25,927","7,4368",...,"4,9263","90,8921","10,1055","1,598",NaN,NaN,"37,42","9,6692","1,1986","17,0967"
14,15/04/2021,"1,5448","1,9558","6,7631","1,4955","1,1046","7,8129",NaN,"25,942","7,4372",...,"4,925","92,2336","10,1298","1,5974",NaN,NaN,"37,376","9,7111","1,197","17,0453"

In [14]:
df = pandas.DataFrame(columns=['date','cur'])
for i in dates.columns:
    dates_tmp = dates[dates[i] != '-']
    df['date'] = dates_tmp[0].max()

In [16]:
df.head(3)

Empty DataFrame
Columns: [date, cur]
Index: []

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook